export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
  };

const AboutPage = () => {
    return (
        <div>
          <h1 className="text-4xl text-center my-5">About Page</h1>
        </div>
    );
};

export default AboutPage;